language: node_js
node_js:
- '0.12'
scripts:
- "./node_modules/.bin/browserify -o build/bundle.js -d ."
deploy:
  provider: heroku
  api_key:
    secure: h4VkVqzXWci8C6j4aFjgzrmehnWdRIGOnwMpqMhysw83zjt3z8hSingVdrAhhKOagCO+dXBV04wPBO1lFr9FUXA9PQUAPkWrg9u4+hyaXM8YReH02qAn2BY81tzmd5q1s2o2QQyi60+qXyndXdcJ2RzGGTgIn3FCbqnu9OrN45Y=
  app: markdown-fluxible
  on:
    repo: kanedam/markdown-fluxible
sudo: false
